### ISSUE TITLE
Timeout while installing

### ISSUE THREAD

**Issue by stebo85** [graydenshand/eks_jupyterhub#5]
Dear @graydenshand ,

After the recent upgrades I am getting this timeout: I tried now multiple times in different regions - any idea what this could be?
```
1:15:16 am | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart             | Jupyterhub/Applica...t/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'Release "jupyterhub" does not exist. Installing it now.\nError: timed out
waiting for the condition\n'

Logs: /aws/lambda/Jupyterhub-Application-awscdkawsek-Handler886CB40B-fUJVR8fUEi3o

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: 393d4325-76d0-441a-a36d-754b05f0312c)
```

**Comment by stebo85** [comment]
when looking in this logfile /aws/lambda/Jupyterhub-Application-awscdkawsek-Handler886CB40B-fUJVR8fUEi3o

The error right before that is:
```
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
```

**Comment by stebo85** [comment]
scrolling to the beginning of this, it says this about the runtime version:
```
INIT_START Runtime Version: python:3.11.v46	Runtime Version ARN: arn:aws:lambda:ap-southeast-2::runtime:84bc5fe9641102b252ebbfd80d16f2791f7bcca59e26ce68d95066317adf4503
```

looks good to me :? What version worked for you?

**Comment by graydenshand** [comment]
The error message isn't really ringing any bells, what version of aws-cdk are you running? via `cdk --version`

**Comment by stebo85** [comment]
my cdk version is 2.166.0 (build 7bb9203) - what version worked for you?

**Comment by graydenshand** [comment]
Hm I was on 2.160.0 when I tested. I'll upgrade to latest and test it out again.
